name: clj-watson

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 22 * * *'

permissions:
  contents: read

jobs:
  clj-holmes:
    name: Dependency vulnerability scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Dependency scan
        uses: clj-holmes/clj-watson-action@39b8ed306f2c125860cf6e69b6939363689f998c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          clj-watson-sha: "65d928c"
          clj-watson-tag: "v4.0.1"
          database-strategy: github-advisory
          aliases: clojure-lsp,test
          deps-edn-path: deps.edn
          fail-on-result: false
